# Pretrain from Flickr that already trained with 2 weights with small DO
pretrained_path: /home/nmduy/LR2023/HADA_LAVIS/Output/flickr30k/C1_cont_both/best.pth.tar
model_1_name: blip_retrieval
model_1_type: flickr
model_2_name: clip_feature_extractor
model_2_type: ViT-L-14-336
f1_in: 768
f1_out: 256
f2_in: 768
f2_out: 768
ft_trans: [512]
ft_gcn: [512]
ft_com: [512]
ft_itm: [1]
type_gcn: GATv2
concat: False # for TGCN and GATv2
skip: True
n_heads: 4
l2_norm: True
# act_func can be blank (no activate function), relu, swish
act_func: gelu
# weight edge
wfc: 0.9
wfcx: 0.7
wcc: 1.1
wfsl: 1
wcsl: 1
directed_graph: True
# Optimizer
optimizer_choice: adamw
learning_rate: 0.0001
batch_norm: True
dropout: 0.2
grad_clip: -1
weight_decay: 0.02
# Train
mode_train: both
batch_size: 24
num_epoch: 100
early_stop: 5
thres_loss: 0.001
temp: 0.07
# momentum
alpha: 0.4
distill: False
queue_size: 10152
momentum: 0.995
# plateau scheduler
min_lr: 0.00001
factor: 0.2
patience: 4
# cosine scheduler <-- if T0 > 0 else using plateau scheduler
T0: 30
Tmul: 2
Tmax: -1
# Margin Loss
# Negative loglikelihood classification (emb)
weight_nll_loss: 1
weight_itm_loss: 1
use_weighted_retrieval: False
device: cuda
# Other
out_dir: Output